services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    mem_reservation: 512m
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env
    volumes:
      - ./config:/config
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: homeassistant_network
    driver: bridge
